### POST a new note
POST http://localhost:3001/api/notes HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZseGEiLCJpZCI6IjYxYmJhYmI4NTRkMTRiOWM5MTA2MjQ1NCIsImlhdCI6MTYzOTY5MTkyOX0.mdIlx-2jO6i4ayQzTujvo636Gd-S4YBbXb3kgmoKsZI

{
    "content": "Maybe working now",
    "important": true
}

### Get all notes
GET http://localhost:3001/api/notes